# Generated by Django 5.1.4 on 2026-01-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sorteo', models.DateField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganadores', to='participantes.participante')),
            ],
        ),
    ]
